name: Selenium Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      # ==========================================================
      # NEW STEP: Install the virtual screen for pyautogui
      # ==========================================================
      - name: Install Xvfb (Virtual Screen)
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Keyword-Driven Test Data
        run: python create_fresh_test_data.py

      - name: Enforce Headless Mode for Tests
        run: |
          sed -i 's/^headless_mode = False/headless_mode = True/' selenium_demoblaze_framework/config/config.ini

      - name: Run Pytest and Generate Reports
        env:
          PYTHONPATH: ${{ github.workspace }}
        # ==========================================================
        # MODIFIED COMMAND: Run pytest inside the virtual screen
        # ==========================================================
        run: |
          xvfb-run pytest selenium_demoblaze_framework/tests/ --html=reports/test-report.html --alluredir=reports/allure-results

      - name: Upload HTML Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-test-report
          path: reports/test-report.html

      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@v1.7
        continue-on-error: true
        with:
          allure_results: reports/allure-results
          allure_history: allure-history

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report